import manifestJson from "./manifest.json";

/**
 * The village's art, as generated by `pnpm --filter client art` (scripts/art): sizes, anchors and footprints from
 * manifest.json, and the URL of every image (resolved by Vite, so the game loads them lazily).
 *
 * An anchor is the pixel of the sprite that sits on the centre of its map tile (for a building, the tile behind its
 * door). Replacing an image with the artist's keeps working as long as its entry here matches.
 */
export interface SpriteInfo {
  width: number;
  height: number;
  anchor: [number, number];
}

export interface BuildingSprite extends SpriteInfo {
  /** Map tiles the building stands on, relative to the tile behind its door. */
  footprint: [number, number][];
}

export interface DecorationSprite extends SpriteInfo {
  solid: boolean;
}

export interface CharacterSheet {
  frameWidth: number;
  frameHeight: number;
  anchor: [number, number];
  /** Rows: facing d turns d × 45° from the map's +y towards +x. */
  directions: number;
  /** Columns of each animation. */
  idle: number[];
  walk: number[];
}

export const manifest = manifestJson as unknown as {
  tile: { width: number; height: number };
  /** Ground tiles in tileset order (Tiled gid = index + 1). */
  tiles: string[];
  buildings: Record<string, BuildingSprite>;
  decorations: Record<string, DecorationSprite>;
  characters: Record<string, CharacterSheet>;
};

const urls = import.meta.glob("./**/*.{png,webp}", { eager: true, query: "?url", import: "default" }) as Record<string, string>;

/** URL of an image under src/game/assets, e.g. `assetUrl("buildings/town-center.webp")` (sprites are WebP, the ground tileset PNG). */
export function assetUrl(path: string): string {
  const url = urls[`./${path}`];
  if (!url) throw new Error(`Unknown asset ${path}`);
  return url;
}

/** The sprite of a building: its under-construction variant when there is one. */
export const buildingSpriteKey = (slug: string, underConstruction: boolean) => (underConstruction && manifest.buildings[`${slug}-construction`] ? `${slug}-construction` : slug);
