/**
 * The village map (a Tiled isometric map generated by scripts/art/map.mjs): its ground, where nobody can walk, the
 * scenery and the doors, plus the projection between map tiles and screen pixels.
 *
 * Tile (x, y): x grows down-right on screen and y down-left. `project` gives the pixel of a tile's centre.
 */
export interface Tile {
  x: number;
  y: number;
}

interface TiledProperty {
  name: string;
  value: number | string | boolean;
}
interface TiledObject {
  name: string;
  properties?: TiledProperty[];
}
interface TiledLayer {
  name: string;
  type: "tilelayer" | "objectgroup";
  data?: number[];
  objects?: TiledObject[];
}
export interface TiledMap {
  width: number;
  height: number;
  tilewidth: number;
  tileheight: number;
  layers: TiledLayer[];
}

const tileOf = (object: TiledObject): Tile => {
  const prop = (name: string) => Number(object.properties?.find((p) => p.name === name)?.value ?? 0);
  return { x: prop("tileX"), y: prop("tileY") };
};

export class IsoMap {
  readonly width: number;
  readonly height: number;
  readonly tileWidth: number;
  readonly tileHeight: number;
  /** Tileset frame of each tile (gid - 1), row by row. */
  readonly ground: number[];
  private readonly blocked: boolean[];
  readonly decoration: { key: string; tile: Tile }[];
  /** Door tiles by building slug, as the map was generated (the on-chain Building table is the source of truth). */
  readonly doors: Map<string, Tile>;

  constructor(map: TiledMap) {
    const layer = (name: string) => map.layers.find((l) => l.name === name);
    this.width = map.width;
    this.height = map.height;
    this.tileWidth = map.tilewidth;
    this.tileHeight = map.tileheight;
    this.ground = (layer("ground")?.data ?? []).map((gid) => gid - 1);
    this.blocked = (layer("collision")?.data ?? []).map((gid) => gid !== 0);
    this.decoration = (layer("decoration")?.objects ?? []).map((o) => ({ key: o.name, tile: tileOf(o) }));
    this.doors = new Map((layer("doors")?.objects ?? []).map((o) => [o.name, tileOf(o)]));
  }

  inside({ x, y }: Tile) {
    return x >= 0 && y >= 0 && x < this.width && y < this.height;
  }

  walkable(tile: Tile) {
    return this.inside(tile) && !this.blocked[tile.y * this.width + tile.x];
  }

  /** Blocks or frees tiles at run time (building footprints come from the chain). */
  setBlocked(tile: Tile, blocked: boolean) {
    if (this.inside(tile)) this.blocked[tile.y * this.width + tile.x] = blocked;
  }

  /** 0 = walkable, 1 = blocked, row by row (the grid pathfinding works on). */
  grid(): number[][] {
    return Array.from({ length: this.height }, (_, y) => Array.from({ length: this.width }, (_, x) => (this.blocked[y * this.width + x] ? 1 : 0)));
  }

  /** Pixel of the centre of a tile (fractions allowed, for sprites moving between tiles). */
  project({ x, y }: Tile) {
    return { x: ((x - y) * this.tileWidth) / 2, y: ((x + y + 1) * this.tileHeight) / 2 };
  }

  /** The tile under a pixel. */
  unproject(px: number, py: number): Tile {
    const a = px / (this.tileWidth / 2);
    const b = py / (this.tileHeight / 2) - 1;
    return { x: Math.round((a + b) / 2), y: Math.round((b - a) / 2) };
  }

  /** Pixel bounds of the whole map. */
  bounds() {
    const halfW = (this.width * this.tileWidth) / 2;
    return { x: -halfW, y: 0, width: halfW * 2, height: this.height * this.tileHeight };
  }
}

/** Facing row of a character sheet for a step (dx, dy): row d turns d × 45° from the map's +y towards +x. */
export function facing(dx: number, dy: number): number {
  const turns = Math.round(Math.atan2(dx, dy) / (Math.PI / 4));
  return (turns + 8) % 8;
}
