/**
 * Copies the compiled ABIs into src/abis/generated as `as const` TypeScript so viem can infer types.
 * Run after `pnpm --filter contracts build` and `pnpm --filter @aldea/council build`:
 *   pnpm --filter @aldea/shared abis
 * The generated files are committed so consumers do not need Foundry to typecheck.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packages = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const out = join(packages, "shared", "src", "abis", "generated");

const sources: Record<string, string> = {
  // World entry points (namespaced aldea__* functions and every system error)
  IWorld: "contracts/out/IWorld.sol/IWorld.abi.json",
  // Systems emit their own events from their own addresses (non-root namespace)
  CharacterSystem: "contracts/out/CharacterSystem.sol/CharacterSystem.abi.json",
  MovementSystem: "contracts/out/MovementSystem.sol/MovementSystem.abi.json",
  FounderSystem: "contracts/out/FounderSystem.sol/FounderSystem.abi.json",
  // The shared rails, as published in @adasouls/protocol
  AlmaAnchorRegistry: "@adasouls/protocol/abis/AlmaAnchorRegistry.json",
  AtlasRegistry: "@adasouls/protocol/abis/AtlasRegistry.json",
  AldeaCouncilExecutor: "council/out/AldeaCouncilExecutor.sol/AldeaCouncilExecutor.json",
};

const require = createRequire(import.meta.url);
const resolve = (source: string) => (source.startsWith("@") ? require.resolve(source) : join(packages, source));
const origin = (source: string) => (source.startsWith("@") ? source : `packages/${source}`);

for (const [name, source] of Object.entries(sources)) {
  const json = JSON.parse(readFileSync(resolve(source), "utf8"));
  const abi = Array.isArray(json) ? json : json.abi;
  const constName = `${name[0]!.toLowerCase()}${name.slice(1)}Abi`;
  writeFileSync(
    join(out, `${name}.ts`),
    `// Generated by packages/shared/scripts/export-abis.ts from ${origin(source)}. Do not edit.\nexport const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  console.log(`${name}: ${abi.length} entries`);
}
