/**
 * Copies the compiled ABIs into src/abis/generated as `as const` TypeScript so viem can infer types.
 * Run after `pnpm --filter contracts build` and `pnpm --filter @aldea/protocol build`:
 *   pnpm --filter @aldea/shared abis
 * The generated files are committed so consumers do not need Foundry to typecheck.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const out = join(root, "shared", "src", "abis", "generated");

const sources: Record<string, string> = {
  // World entry points (namespaced aldea__* functions and every system error)
  IWorld: "contracts/out/IWorld.sol/IWorld.abi.json",
  // Systems emit their own events from their own addresses (non-root namespace)
  CharacterSystem: "contracts/out/CharacterSystem.sol/CharacterSystem.abi.json",
  MovementSystem: "contracts/out/MovementSystem.sol/MovementSystem.abi.json",
  FounderSystem: "contracts/out/FounderSystem.sol/FounderSystem.abi.json",
  AlmaAnchorRegistry: "protocol/out/AlmaAnchorRegistry.sol/AlmaAnchorRegistry.json",
  AtlasRegistry: "protocol/out/AtlasRegistry.sol/AtlasRegistry.json",
  AldeaCouncilExecutor: "protocol/out/AldeaCouncilExecutor.sol/AldeaCouncilExecutor.json",
};

for (const [name, rel] of Object.entries(sources)) {
  const json = JSON.parse(readFileSync(join(root, rel), "utf8"));
  const abi = Array.isArray(json) ? json : json.abi;
  const constName = `${name[0]!.toLowerCase()}${name.slice(1)}Abi`;
  writeFileSync(
    join(out, `${name}.ts`),
    `// Generated by packages/shared/scripts/export-abis.ts from packages/${rel}. Do not edit.\nexport const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  console.log(`${name}: ${abi.length} entries`);
}
